# config/services.yaml
services:

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  VentureLeap\LeapOneGlobalBundle\:
    resource: '../../../src/*'

  VentureLeap\LeapOneGlobalBundle\Services\UserApiProvider:
    arguments:
      $userServiceHost: '%env(string:LEAP_ONE_ENDPOINT_URL)%'
      $applicationId: '%env(string:LEAP_ONE_APP_ID)%'
      $applicationSecret: '%env(string:LEAP_ONE_APP_SECRET)%'

  VentureLeap\UserService\Api\UserApi:
    factory: ['@VentureLeap\LeapOneGlobalBundle\Services\UserApiProvider', 'getUserApi']


  VentureLeap\LeapOneGlobalBundle\Services\ConfigurationApiProvider:
    class: App\Services\ConfigurationService\ConfigurationServiceConfiguration
    arguments:
      $configurationServiceHost: '%env(string:LEAP_ONE_ENDPOINT_URL)%'
      $applicationId: '%env(string:LEAP_ONE_APP_ID)%'
      $username: '%env(string:LEAP_ONE_BASIC_USERNAME)%'
      $password: '%env(string:LEAP_ONE_BASIC_PASSWORD)%'
