# config/services.yaml
services:

  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  VentureLeap\LeapOnePhpSdk\:
    resource: '../../../src/*'

  # MESSENGER
  VentureLeap\LeapOnePhpSdk\Services\ApiProvider\MessengerApiProvider:
    arguments:
      $endpoint: '%env(string:LEAP_ONE_ENDPOINT_URL)%'

  VentureLeap\MessengerService\Api\MessageApi:
    factory: [ '@VentureLeap\LeapOnePhpSdk\Services\ApiProvider\MessengerApiProvider', 'getMessageApi' ]

  VentureLeap\MessengerService\Api\TemplateApi:
    factory: [ '@VentureLeap\LeapOnePhpSdk\Services\ApiProvider\MessengerApiProvider', 'getTemplateApi' ]

  VentureLeap\MessengerService\Api\ConfigurationEntryApi:
    factory: [ '@VentureLeap\LeapOnePhpSdk\Services\ApiProvider\MessengerApiProvider', 'getConfigurationEntryApi' ]

  # ORDER
  VentureLeap\LeapOnePhpSdk\Services\ApiProvider\OrderApiProvider:
    arguments:
      $endpoint: '%env(string:LEAP_ONE_ENDPOINT_URL)%'

  VentureLeap\OrderService\Api\OrderApi:
    factory: [ '@VentureLeap\LeapOnePhpSdk\Services\ApiProvider\OrderApiProvider', 'getOrderApi' ]

  VentureLeap\OrderService\Api\OrderProductApi:
    factory: [ '@VentureLeap\LeapOnePhpSdk\Services\ApiProvider\OrderApiProvider', 'getOrderProductApi' ]

  VentureLeap\OrderService\Api\ConfigurationEntryApi:
    factory: [ '@VentureLeap\LeapOnePhpSdk\Services\ApiProvider\OrderApiProvider', 'getConfigurationEntryApi' ]

  # USER
  VentureLeap\LeapOnePhpSdk\Services\ApiProvider\UserApiProvider:
    arguments:
      $endpoint: '%env(string:LEAP_ONE_ENDPOINT_URL)%'

  VentureLeap\UserService\Api\UserApi:
    factory: [ '@VentureLeap\LeapOnePhpSdk\Services\ApiProvider\UserApiProvider', 'getUserApi' ]

  VentureLeap\UserService\Api\ConfigurationEntryApi:
    factory: [ '@VentureLeap\LeapOnePhpSdk\Services\ApiProvider\UserApiProvider', 'getConfigurationEntryApi' ]

  VentureLeap\UserService\Api\SocialAuthenticationApi:
    factory: [ '@VentureLeap\LeapOnePhpSdk\Services\ApiProvider\UserApiProvider', 'getSocialAuthenticationApi' ]

  # AUDIT LOG
  VentureLeap\LeapOnePhpSdk\Services\ApiProvider\AuditLogApiProvider:
    arguments:
      $endpoint: '%env(string:LEAP_ONE_ENDPOINT_URL)%'

  VentureLeap\AuditLogService\Api\AuditLogEntryApi:
    factory: [ '@VentureLeap\LeapOnePhpSdk\Services\ApiProvider\AuditLogApiProvider', 'getAuditLogEntryApi' ]

  VentureLeap\AuditLogService\Api\ConfigurationEntryApi:
    factory: [ '@VentureLeap\LeapOnePhpSdk\Services\ApiProvider\AuditLogApiProvider', 'getConfigurationEntryApi' ]


  # Product
  VentureLeap\LeapOnePhpSdk\Services\ApiProvider\ProductApiProvider:
    arguments:
      $endpoint: '%env(string:LEAP_ONE_ENDPOINT_URL)%'

  VentureLeap\ProductService\Api\ProductApi:
    factory: [ '@VentureLeap\LeapOnePhpSdk\Services\ApiProvider\ProductApiProvider', 'getProductApi' ]

  VentureLeap\ProductService\Api\ProductCategoryApi:
    factory: [ '@VentureLeap\LeapOnePhpSdk\Services\ApiProvider\ProductApiProvider', 'getProductCategoryApi' ]

  VentureLeap\ProductService\Api\PriceListProductApi:
    factory: [ '@VentureLeap\LeapOnePhpSdk\Services\ApiProvider\ProductApiProvider', 'getPriceListProductApi' ]

  VentureLeap\ProductService\Api\PriceListApi:
    factory: [ '@VentureLeap\LeapOnePhpSdk\Services\ApiProvider\ProductApiProvider', 'getPriceListApi' ]

  VentureLeap\LeapOnePhpSdk\Services\ApiProvider\ConfigurationApiProvider:
    arguments:
      $endpoint: '%env(string:LEAP_ONE_ENDPOINT_URL)%'

  VentureLeap\ConfigurationService\Api\ConfigurationEntryApi:
    factory: [ '@VentureLeap\LeapOnePhpSdk\Services\ApiProvider\ConfigurationApiProvider', 'getConfigurationEntryApi' ]

  # TOKEN
  VentureLeap\LeapOnePhpSdk\Services\ApiProvider\TokenApiProvider:
    arguments:
      $endpoint: '%env(string:LEAP_ONE_ENDPOINT_URL)%'

  VentureLeap\ConfigurationService\Api\TokenApi:
    factory: [ '@VentureLeap\LeapOnePhpSdk\Services\ApiProvider\TokenApiProvider', 'getTokenApi' ]

  VentureLeap\LeapOnePhpSdk\Services\TokenProvider\TokenProvider:
    arguments:
      $applicationId: '%env(string:LEAP_ONE_APP_ID)%'
      $applicationSecret: '%env(string:LEAP_ONE_APP_SECRET)%'

  # FORM AUTHENTICATION
  leap_one.login_form_authenticator:
    class: VentureLeap\LeapOnePhpSdk\Services\Security\LoginFormAuthenticator
    public: true
    arguments:
      $loginRoute: 'leap_one_user_login'
    tags: [ 'leap_one.login_form_authenticators' ]

